Repository database-mesh/pisanix, pull requests merged in 2022-05, with the labels that each got.

#3 fix links and schedule format in introduction
  README.md
  docs/.docusaurus/client-manifest.json
  docs/.docusaurus/docusaurus.config.js
  docs/docs/intro.md
  docs/docusaurus.config.js
Labels: size/M

#4 update: update loadbalancer & mysql protocol document
  docs/docs/Features/loadbalancer.md
  docs/docs/Features/mysql-protocol.md
Labels: size/S

#7 fix(parser): fix lex error in parser
  pisa-proxy/parser/mysql/build.rs
  pisa-proxy/parser/mysql/src/charsets.rs
  pisa-proxy/parser/mysql/src/grammar.y
  pisa-proxy/parser/mysql/src/ident.rs
  pisa-proxy/parser/mysql/src/lex.rs
  pisa-proxy/parser/mysql/src/parser.rs
Labels: size/XL

#6 fix duration metrics and add contribution guide
  CONTRIBUTING.md
  pisa-proxy/runtime/mysql/src/server/server.rs
Labels: size/M

#8 chore(docs): uddate docs for sql_breaker and parser
  docs/docs/Features/sql-breaker-limit.md
  docs/docs/Features/sql-parser.md
Labels: size/S

#9 refactor: rename limit to concurrency_control
  pisa-proxy/app/api/src/config.rs
  pisa-proxy/app/config/Cargo.toml
  pisa-proxy/app/config/src/config.rs
  pisa-proxy/examples/example-config.toml
  pisa-proxy/plugin/src/build_phase.rs
  pisa-proxy/plugin/src/circuit_breaker/mod.rs
  pisa-proxy/plugin/src/concurrency_control/mod.rs
  pisa-proxy/plugin/src/config.rs
  pisa-proxy/plugin/src/err.rs
  pisa-proxy/plugin/src/lib.rs
  pisa-proxy/plugin/src/tests/mod.rs
  pisa-proxy/proxy/src/proxy.rs
  pisa-proxy/runtime/mysql/src/server/server.rs
Labels: size/L

#10 update: update sql-breaker-limit and fix sql-parser doc
  docs/.docusaurus/client-manifest.json
  docs/.docusaurus/client-modules.js
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-features-mysql-protocol-md-bd3.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-features-sql-breaker-limit-md-8e8.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/site-docs-features-sql-parser-md-711.json
  docs/.docusaurus/docusaurus-plugin-content-docs/default/version-current-metadata-prop-751.json
  docs/.docusaurus/docusaurus.config.js
  docs/.docusaurus/registry.js
  docs/.docusaurus/routes.js
  docs/.docusaurus/routesChunkNames.json
  docs/docs/Features/sql-breaker-limit.md
  docs/docs/Features/sql-parser.md
Labels: size/L

#12 add FOSSA badge and rust-toolchain and pisa-controller
  .gitignore
  README.md
  docs/docs/Features/sql-circuit-breaker-and-concurrency-control.md
  pisa-controller/README.md
  pisa-controller/charts/pisa-controller/.helmignore
  pisa-controller/charts/pisa-controller/Chart.yaml
  pisa-controller/charts/pisa-controller/crds/core.database-mesh.io_databaseendpoints.yaml
  pisa-controller/charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml
  pisa-controller/charts/pisa-controller/crds/core.database-mesh.io_virtualdatabases.yaml
  pisa-controller/charts/pisa-controller/templates/deployment.yaml
  pisa-controller/charts/pisa-controller/templates/rbac.yaml
  pisa-controller/charts/pisa-controller/templates/service.yaml
  pisa-controller/charts/pisa-controller/templates/webhook/admission-webhook-apiservice.yaml
  pisa-controller/charts/pisa-controller/templates/webhook/admission-webhook-configuration.yaml
  pisa-controller/charts/pisa-controller/values.yaml
  pisa-controller/cmd/app/basicServer.go
  pisa-controller/cmd/app/configServer.go
  pisa-controller/cmd/app/webhookServer.go
  pisa-controller/cmd/main.go
  pisa-controller/deploy/config-sample.yaml
  pisa-controller/deploy/sample.yaml
  pisa-controller/go.mod
  pisa-controller/go.sum
  pisa-controller/pkg/config/config.go
  pisa-controller/pkg/config/types.go
  pisa-controller/pkg/webhook/inject.go
  pisa-proxy/rust-toolchain
Labels: size/XXL

#15 fix: path in pisa-proxy dockerfile
  pisa-proxy/hack/Dockerfile
Labels: bug, size/XS

#16 fix: binary artifact of pisa-controller
  pisa-controller/hack/Dockerfile
Labels: bug, size/XS

#19 Refactor with default config, remove pprof handler and variable rename
  pisa-proxy/Cargo.lock
  pisa-proxy/app/api/src/config.rs
  pisa-proxy/app/config/src/config.rs
  pisa-proxy/http/Cargo.toml
  pisa-proxy/http/src/controllers/pprof.rs
  pisa-proxy/http/src/http.rs
  pisa-proxy/parser/src/lib.rs
  pisa-proxy/plugin/src/build_phase.rs
  pisa-proxy/plugin/src/concurrency_control/mod.rs
  pisa-proxy/plugin/src/config.rs
  pisa-proxy/plugin/src/lib.rs
  pisa-proxy/plugin/src/tests/mod.rs
  pisa-proxy/proxy/src/proxy.rs
  pisa-proxy/runtime/mysql/src/server/server.rs
Labels: size/L, refactor, pisa-proxy

#20 Fix(parser): fix lex parse '@'
  pisa-proxy/parser/mysql/src/lex.rs
Labels: size/M

#21 parser: support deallocate prepare
  pisa-proxy/parser/mysql/src/ast/dml.rs
  pisa-proxy/parser/mysql/src/ast/mod.rs
  pisa-proxy/parser/mysql/src/grammar.y
  pisa-proxy/parser/mysql/src/parser.rs
Labels: size/M, pisa-proxy, sql-parser

#22 refactor: split different runtime into different package
  pisa-controller/cmd/main.go
  pisa-controller/cmd/pisa-controller/core/core.go
  pisa-controller/cmd/pisa-controller/main.go
  pisa-controller/cmd/pisa-controller/proxy/proxy.go
  pisa-controller/cmd/pisa-controller/webhook/webhook.go
  pisa-controller/pkg/core/core.go
  pisa-controller/pkg/kubernetes/client.go
  pisa-controller/pkg/kubernetes/types.go
  pisa-controller/pkg/proxy/config.go
  pisa-controller/pkg/proxy/proxy.go
  pisa-controller/pkg/proxy/types.go
  pisa-controller/pkg/webhook/api_check.go
  pisa-controller/pkg/webhook/injection.go
  pisa-controller/pkg/webhook/webhook.go
Labels: size/XL, refactor, pisa-controller

#23 Move the charts to root
  charts/pisa-controller/.helmignore
  charts/pisa-controller/Chart.yaml
  charts/pisa-controller/crds/core.database-mesh.io_databaseendpoints.yaml
  charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml
  charts/pisa-controller/crds/core.database-mesh.io_virtualdatabases.yaml
  charts/pisa-controller/templates/deployment.yaml
  charts/pisa-controller/templates/rbac.yaml
  charts/pisa-controller/templates/service.yaml
  charts/pisa-controller/templates/webhook/admission-webhook-apiservice.yaml
  charts/pisa-controller/templates/webhook/admission-webhook-configuration.yaml
  charts/pisa-controller/values.yaml
Labels: size/XS

#25 Fix(runtime) memory leak
  pisa-proxy/runtime/mysql/src/mysql.rs
  pisa-proxy/runtime/mysql/src/server/server.rs
Labels: size/S

#26 Add some comments and fix type convertion
  charts/pisa-controller/crds/core.database-mesh.io_databaseendpoints.yaml
  charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml
  charts/pisa-controller/crds/core.database-mesh.io_virtualdatabases.yaml
  example/config-sample.yaml
  example/sample.yaml
  pisa-controller/pkg/kubernetes/types.go
  pisa-controller/pkg/proxy/config.go
  pisa-controller/pkg/proxy/proxy.go
  pisa-controller/pkg/proxy/types.go
Labels: size/L, pisa-controller

#27 refactor kubernetes client initialization using singleton
  charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml
  pisa-controller/cmd/pisa-controller/main.go
  pisa-controller/pkg/kubernetes/client.go
  pisa-controller/pkg/kubernetes/types.go
  pisa-controller/pkg/proxy/config.go
  pisa-controller/pkg/proxy/proxy.go
Labels: size/M

#28 Fix nil pointer err for get kubernetes client
  pisa-controller/pkg/kubernetes/client.go
Labels: size/XS, pisa-controller

#29 Fix(protocol): fix hang when return `Prepare` return error
  pisa-proxy/protocol/mysql/src/client/conn.rs
  pisa-proxy/protocol/mysql/src/client/stmt.rs
  pisa-proxy/protocol/mysql/src/err.rs
  pisa-proxy/runtime/mysql/src/server/server.rs
Labels: bug, size/S, pisa-proxy

#30 FIX: Fix helm args and port name for new flag
  charts/pisa-controller/templates/deployment.yaml
  charts/pisa-controller/templates/service.yaml
Labels: size/XS, pisa-controller

#32 Fix cargo build failed caused by no authentication
  pisa-proxy/Cargo.lock
  pisa-proxy/Cargo.toml
Labels: size/XS

#33 Fix(runtime): fix get conn error in fsm
  pisa-proxy/protocol/mysql/src/client/conn.rs
  pisa-proxy/proxy/pool/src/conn_pool.rs
  pisa-proxy/runtime/mysql/src/server/server.rs
  pisa-proxy/runtime/mysql/src/transaction_fsm.rs
Labels: bug, size/M
